# Generated by Django 2.2.5 on 2021-06-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
        ('users', '0004_auto_20210622_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studios.Studio'),
        ),
    ]
