# Generated by Django 2.2.5 on 2021-06-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210623_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
    ]
