# Generated by Django 2.2.5 on 2021-06-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_remove_channel_artist'),
        ('users', '0008_remove_user_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel'),
        ),
    ]
