# Generated by Django 2.2.5 on 2021-06-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artist',
            new_name='busker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='studio',
        ),
    ]
