# Generated by Django 2.2.5 on 2021-06-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TimeStampedModel')),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='studio',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studio',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
