# Generated by Django 2.2.5 on 2021-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_auto_20210622_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='studios.Post'),
        ),
    ]
