# Generated by Django 2.2.5 on 2021-06-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_auto_20210622_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='avatar',
            new_name='image',
        ),
    ]
