# Generated by Django 2.2.5 on 2021-06-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_auto_20210623_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='posts',
        ),
        migrations.AddField(
            model_name='studio',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='studios.Post'),
        ),
    ]
