# Generated by Django 2.2.5 on 2021-06-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studios', '0009_auto_20210623_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, upload_to='studio_photos'),
        ),
    ]
