# Generated by Django 2.2.5 on 2021-06-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20210617_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='resolution',
        ),
        migrations.AddField(
            model_name='channel',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.Resolution'),
        ),
    ]
