# Generated by Django 2.2.5 on 2021-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20210617_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
