# Generated by Django 2.2.5 on 2021-06-21 18:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
