# Generated by Django 2.2.5 on 2021-06-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20210622_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='artist',
        ),
    ]
