# Generated by Django 2.2.5 on 2021-06-22 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0006_remove_channel_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='genre',
            field=models.ManyToManyField(blank=True, to='channels.Genre'),
        ),
    ]
