# Generated by Django 2.2.5 on 2021-06-25 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_channel_channel_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, upload_to='channel_photos'),
        ),
    ]
